// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultiClinicAPI.Data;

#nullable disable

namespace multiclinic_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524002700_AddUniqueIndexes")]
    partial class AddUniqueIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultiClinicAPI.Models.Agendamento", b =>
                {
                    b.Property<int>("ID_Agendamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Agendamento"));

                    b.Property<DateTime>("Data_Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Medico")
                        .HasColumnType("int");

                    b.Property<int>("ID_Paciente")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Agendamento");

                    b.HasIndex("ID_Medico");

                    b.HasIndex("ID_Paciente");

                    b.ToTable("Agendamentos");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Avaliacao", b =>
                {
                    b.Property<int>("ID_Avaliacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Avaliacao"));

                    b.Property<int>("ID_Agendamento")
                        .HasColumnType("int");

                    b.Property<int>("Nota")
                        .HasColumnType("int");

                    b.HasKey("ID_Avaliacao");

                    b.HasIndex("ID_Agendamento")
                        .IsUnique();

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Especialidade", b =>
                {
                    b.Property<int>("ID_Especialidade")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Especialidade"));

                    b.Property<string>("Nome_Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Especialidade");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Prontuario", b =>
                {
                    b.Property<int>("ID_Prontuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Prontuario"));

                    b.Property<string>("Evolucao_Clinica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Agendamento")
                        .HasColumnType("int");

                    b.Property<string>("Prescricao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Prontuario");

                    b.HasIndex("ID_Agendamento")
                        .IsUnique();

                    b.ToTable("Prontuarios");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha_Hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Perfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Usuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Medico", b =>
                {
                    b.HasBaseType("MultiClinicAPI.Models.Usuario");

                    b.Property<string>("CRM")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ID_Especialidade")
                        .HasColumnType("int");

                    b.HasIndex("CRM")
                        .IsUnique()
                        .HasFilter("[CRM] IS NOT NULL");

                    b.HasIndex("ID_Especialidade");

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Paciente", b =>
                {
                    b.HasBaseType("MultiClinicAPI.Models.Usuario");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Data_Nascimento")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Score_Assiduidade")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasIndex("CPF")
                        .IsUnique()
                        .HasFilter("[CPF] IS NOT NULL");

                    b.ToTable("Pacientes", (string)null);
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Agendamento", b =>
                {
                    b.HasOne("MultiClinicAPI.Models.Medico", "Medico")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ID_Medico")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MultiClinicAPI.Models.Paciente", "Paciente")
                        .WithMany("Agendamentos")
                        .HasForeignKey("ID_Paciente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medico");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Avaliacao", b =>
                {
                    b.HasOne("MultiClinicAPI.Models.Agendamento", "Agendamento")
                        .WithOne("Avaliacao")
                        .HasForeignKey("MultiClinicAPI.Models.Avaliacao", "ID_Agendamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Prontuario", b =>
                {
                    b.HasOne("MultiClinicAPI.Models.Agendamento", "Agendamento")
                        .WithOne("Prontuario")
                        .HasForeignKey("MultiClinicAPI.Models.Prontuario", "ID_Agendamento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Medico", b =>
                {
                    b.HasOne("MultiClinicAPI.Models.Especialidade", "Especialidade")
                        .WithMany("Medicos")
                        .HasForeignKey("ID_Especialidade")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MultiClinicAPI.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("MultiClinicAPI.Models.Medico", "ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Paciente", b =>
                {
                    b.HasOne("MultiClinicAPI.Models.Usuario", null)
                        .WithOne()
                        .HasForeignKey("MultiClinicAPI.Models.Paciente", "ID_Usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Agendamento", b =>
                {
                    b.Navigation("Avaliacao");

                    b.Navigation("Prontuario");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Especialidade", b =>
                {
                    b.Navigation("Medicos");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Medico", b =>
                {
                    b.Navigation("Agendamentos");
                });

            modelBuilder.Entity("MultiClinicAPI.Models.Paciente", b =>
                {
                    b.Navigation("Agendamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
